### ISSUE TITLE
How the create The .png texture?

### ISSUE THREAD

**Issue by Ants-double** [MikesWei/CesiumMeshVisualizer#1]
I see the volumer endering use a *.png to mipmaping the  cubeTex: "./*.png", ,Now I have the Volume data .But i can't generat the png image. Help.tell me how to change the RAW data to png texture.Thank you.

**Comment by MikesWei** [comment]
see https://github.com/lebarba/WebGLVolumeRendering/tree/master/3DTextureConverter

**Comment by MikesWei** [comment]
JavaScript code:     

          function convert3DTexture(rawData, width, height, depth, flipY) {
            var newWidth = width * maxTilesWidth;
            var newHeight = height * maxTilesHeight;
            var canvas = document.createElement('canvas');
            canvas.height = newHeight;
            canvas.width = newWidth;
            var ctx = canvas.getContext('2d');
            var imageData = ctx.getImageData(0, 0, newWidth, newHeight);

            var realPosX, realPosY;
            var index = 0;

            for (var z = 0; z < depth; z++) {
                for (var y = 0; y < height; y++) {
                    for (var x = 0; x < width; x++) {
                        var value = rawData[index++];

                        realPosX = x + (z % maxTilesHeight) * width;

                        var yPos;
                        if (flipY) {
                            yPos = height - y - 1;
                        }
                        else {
                            yPos = y;
                        }

                        realPosY = yPos + parseInt(z / maxTilesWidth) * height;
                        var colorIdx = realPosX + realPosY * newWidth;
                        colorIdx *= 4;
                        imageData.data[colorIdx] = value;
                        imageData.data[colorIdx + 1] = value;
                        imageData.data[colorIdx + 2] = value;
                        imageData.data[colorIdx + 3] = value;

                    }
                }
            }
            ctx.putImageData(imageData, 0, 0);
            return canvas;
        }

**Comment by Ants-double** [comment]
ye. i use the C# code generate the texture ,it's work Thank you.
