### ISSUE TITLE
用threejs生成了3D文字，但是使用scene.pick无法获取

### ISSUE THREAD

**Issue by lijuhong1981** [MikesWei/CesiumMeshVisualizer#13]
使用threejs的TextGeometry生成3D文字，在场景中渲染没问题，但是使用scene.pick时，无法拾取到场景中的3D文字，该如何解决？
![QQ截图20200102162826](https://user-images.githubusercontent.com/3949154/71658033-4f21d280-2d7d-11ea-9690-96c608c50eeb.png)

**Comment by thanghps** [comment]
Dear lijuhong,

I have also this issue but with MessVisualize. I add via viewer.scene.primitives.add(meshVisualizer);
And iam unable to pick the meshVisualizer.

Do you have the solution for this?

Thank you very much

**Comment by MikesWei** [comment]
The bug has been fixed.
