### ISSUE TITLE
示例代码有错

### ISSUE THREAD

**Issue by vellengs** [MikesWei/CesiumMeshVisualizer#14]
![image](https://user-images.githubusercontent.com/5743338/82208673-86fd7100-993e-11ea-84f9-34b0e456a5b2.png)

**Comment by MikesWei** [comment]
哪一个示例？

**Comment by vellengs** [comment]
https://mikeswei.github.io/CesiumMeshVisualizer/App/demo/CSG/index.html
几个例子都有错误，是兼容都问题？
