### ISSUE TITLE
Can I change black to transparent?

### ISSUE THREAD

**Issue by Ants-double** [MikesWei/CesiumMeshVisualizer#4]
Can I change black to transparent?
![screenshot](https://user-images.githubusercontent.com/32797983/38121387-68abacca-3401-11e8-9520-ee1ca1ea1b53.jpg)
can you help me .I am now one for shader.

**Comment by Ants-double** [comment]
I Change the code 
//The color accumulator.
        vec4 accumulatedColor = vec4(0.2,0.5,0.4,0.1);

        //The alpha value accumulated so far.
        float accumulatedAlpha = 0.0;
then i get the picture .but it's transparent.How make the edge transparent.

**Comment by MikesWei** [comment]
js:
    var materialSecondPass = new MeshMaterial({
        vertexShader: document.getElementById("vertexShaderSecondPass").textContent,
        fragmentShader: document.getElementById("fragmentShaderSecondPass").textContent,
        side: MeshMaterial.Sides.FRONT,
        uniforms: {
            alpha: -1,//
        ...

**Comment by Ants-double** [comment]
I Change the Alpha value but it's work.
